version: '3.8'

services:

  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app/
      - ./app/mediafiles:/usr/src/app/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
      
    environment:
      - POSTGRES_USER=web_menu_admin
      - POSTGRES_PASSWORD=wb-90877zombata
      - POSTGRES_DB=web_menu_db

    # or use .env.dev.db file instead
    # env_file:
    #   - ./.env.dev.db

volumes:
  postgres_data:
  mediafiles: